### ISSUE TITLE
Problem when loading page; e.g. index.php

### ISSUE THREAD

**Issue by sttang112** [pappastech/ospos#3]
A PHP Error was encountered
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 256

**Comment by datumradix** [comment]
Which version you have installed. Have u made any changes to the config file or any of the core classes? This seems a issue with the CI.

**Comment by matolic** [comment]
I get the same error after upgrading from Debian Wheezy to Jessie. The PHP packages went from 5.4 to 5.6.

**Comment by matolic** [comment]
So the problem was with CodeIngnite and the newer version of PHP. I was able to fix the error by changing line 257 to: 

> $return = $_config[0] =& $config;
> return $return;

**Comment by jekkos** [comment]
This change is already in the latest version. So should be fixed.
